### ISSUE TITLE
SDK is not working on agular cli 14.0.0 version

### ISSUE THREAD

**Issue by SevenbitsHarshad** [hashgraph/hedera-sdk-js#1153] opened 2022-06-14 07:05 UTC
### Description

Node Version: 14.19.3
Angular CLI: 13.0.4
SDK version: 2.15.0

It is not working with type script and angular version 

### Steps to reproduce

Node Version: 14.19.3
Angular CLI: 13.0.4
SDK version: 2.15.0

It is not working 

### Additional context

![173510105-5dae910a-58c5-4f29-9c24-64fd4c423919](https://user-images.githubusercontent.com/102015074/173510884-c2a1de05-e761-4624-b779-2837b180239e.png)

### Hedera network

other

### Version

2.15.0

**Comment by danielakhterov** [comment] 2022-06-18 17:12
I think I'm going to need a little bit more context. I tried to reproduce your issue with no luck. This is what I did:
```
ng new my-first-project
npm add @hashgraph/sdk
# Edit src/app/app.component.ts
#
# Add to the top of the file
# import { PrivateKey } from "@hashgraph/sdk";
#
# Update the title to generate a private key
# title = PrivateKey.generate();
ng serve
```
![image](https://user-images.githubusercontent.com/36461294/174449346-aa4ebf10-170f-46f6-9fa8-04509923dcce.png)

Closing as I am not able to reproduce, but can re-open if more context is provided that allows me to reproduce the issue.

**Closed by danielakhterov** 2022-06-18 17:12 UTC
Labels: bug

**Comment by SevenbitsHarshad** [comment] 2022-06-19 04:39
> I think I'm going to need a little bit more context. I tried to reproduce your issue with no luck. This is what I did:
> 
> ```
> ng new my-first-project
> npm add @hashgraph/sdk
> # Edit src/app/app.component.ts
> #
> # Add to the top of the file
> # import { PrivateKey } from "@hashgraph/sdk";
> #
> # Update the title to generate a private key
> # title = PrivateKey.generate();
> ng serve
> ```
> 
> ![image](https://user-images.githubusercontent.com/36461294/174449346-aa4ebf10-170f-46f6-9fa8-04509923dcce.png)
> 
> Closing as I am not able to reproduce, but can re-open if more context is provided that allows me to reproduce the issue.

please share your node version and angular version details

**Comment by SevenbitsHarshad** [comment] 2022-06-19 11:17
> > I think I'm going to need a little bit more context. I tried to reproduce your issue with no luck. This is what I did:
> > ```
> > ng new my-first-project
> > npm add @hashgraph/sdk
> > # Edit src/app/app.component.ts
> > #
> > # Add to the top of the file
> > # import { PrivateKey } from "@hashgraph/sdk";
> > #
> > # Update the title to generate a private key
> > # title = PrivateKey.generate();
> > ng serve
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/36461294/174449346-aa4ebf10-170f-46f6-9fa8-04509923dcce.png)
> > Closing as I am not able to reproduce, but can re-open if more context is provided that allows me to reproduce the issue.
> 
> please share your node version and angular version details

please import the below namespace and check

# import type { AccountId, Client } from "@hashgraph/sdk";
