### ISSUE TITLE
setMaxSupply doesn't work for big numbers 

### ISSUE THREAD

**Issue by Chiptuttofuso** [hashgraph/hedera-sdk-js#825] opened 2021-12-20 09:07 UTC
### Description

When creating a new FINITE token, and you try to call setMaxSupply, it fails is the number is bigger or equal than 100.000.000,0000.
Even when using BigNumber or Long type, it fails in the same way.
Really urgent bug, it is basically blocking the creation of a finite token.

### Steps to reproduce

//Create the transaction and freeze for manual signing
const transaction = await new TokenCreateTransaction()
     .setTokenName("Your Token Name")
     .setTokenSymbol("F")
     .setTreasuryAccountId(treasuryAccountId)
     .setSupplyType(FINITE)
     .setInitialSupply(5000)
     .setMaxSupply(1000000000000)
     .setAdminKey(adminPublicKey)
     .freezeWith(client);

//Sign the transaction with the token adminKey and the token treasury account private key
const signTx =  await (await transaction.sign(adminKey)).sign(treasuryKey);

//Sign the transaction with the client operator private key and submit to a Hedera network
const txResponse = await signTx.execute(client);

//Get the receipt of the transaction
const receipt = await txResponse.getReceipt(client);

//Get the token ID from the receipt
const tokenId = receipt.tokenId;

console.log("The new token ID is " + tokenId);

//v2.0.5

### Hedera network

mainnet, testnet

### Version

2.6.0

### Operating system

macOS

**Comment by danielakhterov** [comment] 2021-12-21 02:36
Although this issue happens at a completely different time, I think it's a duplicate of #813

**Closed by danielakhterov** 2021-12-21 02:36 UTC
Labels: bug
