### ISSUE TITLE
DUPLICATE_TRANSACTION error returned but the tx was successfully exectuted

### ISSUE THREAD

**Issue by anvabr** [hashgraph/hedera-sdk-js#1560] opened 2023-04-18 16:02 UTC
### Description

When minting and/or transferring tokens Guardian occasionally gets `DUPLICATE_TRANSACTION ` error, in the case of a transfer transaction if the code attempts to retry then `SENDER_DOES_NOT_OWN_NFT_SERIAL_NO` error immediately follows this attempt. However the issue is that while returning the error the transaction actually has been successfully executed (Hedera does not seem to be doing rollbacks).

**How can the caller code know when a returned error really means there was an error (and the mint operation has failed), and when it means the mint has actually succeeded?** At a minimum we need facilities to double-check the status of the Tx from Hedera - has it minted or not, ideally we'd need the SDK to correctly report errors please. At present Guardian code assumes the error means this token mint has failed, and because it has to mint a certain number of tokens (as Policy dictates) it goes and mints what it thinks is still needed. We end up with too many tokens minted. 

### Steps to reproduce

This is an intermittent issue, we have observed this multiple times but we are unable to reproduce it on demand. It 'sometimes' happens in our architecture.

[Guardian](https://github.com/hashgraph/guardian) policy execution sometimes can result in minting of large number of tokens. Like all other operations where 'other' systems are involved in Guardian architecture this is performed via 'workers'. The number of workers can be changed depending on the volume of the requests.

### Additional context

An example of a failed transaction (highlighted in red) as shown in Guardian logs

![image](https://user-images.githubusercontent.com/32775532/232833631-1f50cf69-f6c7-4410-bbcc-1962b08f1d05.png)

This is the transaction request, showing from/to which accounts was the transfer

![image (1)](https://user-images.githubusercontent.com/32775532/232834216-f5b9e1ec-b8c2-43d7-86a2-162f9298b3fc.png)

The result of the transaction which has succeeded (in Hedera) while was reported as error by the SDK
![image (2)](https://user-images.githubusercontent.com/32775532/232834513-f88ce8a7-4ea9-46c9-8b63-758b8de38732.png)

The sample transaction: https://testnet.mirrornode.hedera.com/api/v1/transactions/0.0.3656963-1681744331-378584985

The token involved: https://testnet.mirrornode.hedera.com/api/v1/tokens/0.0.4185745/nfts/2561

### Hedera network

testnet

### Version

v2.24.0

### Operating system

None

**Comment by petreze** [comment] 2023-04-21 13:20
Greetings @anvabr, from the things you stated, I understand that you are trying to mint those NFTs asynchronously via the workers you mentioned. I would assume that the problem is because you are not setting explicitly the `transactionId` of each `TokenMintTx`. It is a good practice to make it that way because the `transactionId` is generated based on the accountId of the client that will pay the transaction and the current timestamp (nanos included). And whenever you are trying to do it asynchronously, there is a decent chance that 2 (or more) workers try to execute `TokenMintTx` at the same time, hence, they will generate the same `transactionId` based on the same timestamp. I assume that this is the reason why you get the `DUPLICATE_TRANSACTION`.

Also, because the workers execute the TX simultaneously, the fastest worker will actually submit the transfer transaction, and if being successful, when the second one tries to submit the same TX, it will display `SENDER_DOES_NOT_OWN_NFT_SERIAL_NO` because the first worker has already transferred the NFT with this serial number.

Please provide me an example of your code so I can dig into this further if possible

**Comment by anvabr** [comment] 2023-04-21 14:35
@petreze Thank you for your response, we suspected it was something like this but I am not sure this is exactly the case you describe. It does not matter though what we decided to do with this is to explicitly query the result/status of the transaction if we receive this kind of error. Do you recommend this as a possible approach?

**Comment by petreze** [comment] 2023-04-23 16:09
@anvabr 
This is always a good approach to check the status of the previously submitted transaction if its successful or not

**Comment by petreze** [comment] 2023-04-24 10:12
@anvabr 
If this solves your problem, do you think we can close this issue?

**Closed** 2023-04-25 11:11 UTC
Labels: bug

**Comment by ElijahLynn** [comment] 2023-10-05 20:37
crosslinking relevant issue: https://github.com/hashgraph/hedera-services/issues/304
