### ISSUE TITLE
Incorrect transaction ID reported in errors

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#814] opened 2021-12-16 11:10 UTC
### Description

I've noticed several users reporting errors which contain an invalid transaction id, for example:

```
receipt for transaction 0.0.0@1639643905.876389619 contained error status INVALID_TREASURY_ACCOUNT_FOR_TOKEN
```

note `0.0.0` for the account id part of the transaction id.

### Steps to reproduce

TBD

### Hedera network

mainnet, testnet, previewnet

### Version

v2.6.0

**Comment by danielakhterov** [comment] 2021-12-21 02:41
I haven't seen that in JS for _awhile_. I'm definitely curious as to how to reproduce because when I ran tests today I consistently got the account ID in the receipt.

**Comment by SimiHunjan** [comment] 2022-01-15 00:30
@gregscullard are you still experiencing this issue?

**Comment by SimiHunjan** [comment] 2022-01-19 00:21
Closing for now. Please reopen if you encounter this again.

**Closed by SimiHunjan** 2022-01-19 00:21 UTC
Labels: bug
