### ISSUE TITLE
Adding Node Address Creation Transaction

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-sdk-js#2399] opened 2024-07-12 15:04 UTC
### Problem

Need Node Address Creation Transaction to test solo with network upgrade

### Solution

Implement Node Address Creation Transaction

**Comment by SimiHunjan** [comment] 2024-07-12 18:16
hey @JeffreyDallas ! This is a duplicate of https://github.com/hashgraph/hedera-sdk-js/issues/2335. Closing as duplicate.

**Closed by SimiHunjan** 2024-07-12 18:16 UTC
Labels: enhancement
