### ISSUE TITLE
TransferTransaction.addNftTransfer with NftId as parameter cause TOKEN_ID_REPEATED_IN_TOKEN_LIST

### ISSUE THREAD

**Issue by franfernandez20** [hashgraph/hedera-sdk-js#1233] opened 2022-08-10 21:16 UTC
### Description

I'm detecting the problem when making a `TransferTransaction` with nft transfer. 
If is used as a parameter the type `NftId` when are included in the transaction several nfts some of them with same tokenId (different serial_number) and others with different I'm getting an error at executing, `TOKEN_ID_REPEATED_IN_TOKEN_LIST`. 
If I make exactly the same transfer but using the function `TransferTransaction.addNftTransfer` with params like (String, Number) or (TokenId, Number) all is working as I was expecting.

I think is a possible issue I hope that I'm not misunderstanding something 🙂.

### Steps to reproduce

Option failing
```js
const nftId = new NftId(TokenId.fromString(token_id), serial_number);
new TransferTransaction().addNftTransfer(nftId, sender, receiver);
```
```js
Option working
new TransferTransaction().addNftTransfer(token_id, serial_number, sender, receiver);
```

### Hedera network

testnet

### Version

v2.10.1

### Operating system

Windows

**Comment by danielakhterov** [comment] 2022-08-10 21:19
Before anything else I'd suggest updating to the latest SDK as I believe this was fixed somewhat recently.

**Comment by franfernandez20** [comment] 2022-08-12 07:11
You are right @danielakhterov it is solved in more recent versions, at least since `v2.17.0`.

Thank you. And sorry for the inconveniences.

**Comment by franfernandez20** [comment] 2022-08-19 12:07
I experienced the same problem also in last version. The use case is, when the serial number of both Nfts are the same.
For example:
```js
const nftsToSend = [
  {
    tokenId: "0.0.47857020",
    serial: 45,
  },
    tokenId: "0.0.47857020",
    serial: 44,
  },
  {
    tokenId: "0.0.47857106",
    serial: 44,
  }
// [...]
let trx = new TransferTransaction()
      .addHbarTransfer(receiverId, -amount)
      .addHbarTransfer(senderId, amount);

nfts.forEach((nft) => {
   const nftId = new NftId(TokenId.fromString(nft.tokenId), nft.serial);
   trx.addNftTransfer(nftId, senderId, receiverId);
}); 
```

**Comment by franfernandez20** [comment] 2022-08-20 19:35
I confirmed that this situation is also reproducible with the version of `addNftTransfer` with  4 parameters _(tokenId, serial, sender, receiver)_

```js
const nftsToSend = [
  {
    tokenId: "0.0.47857020",
    serial: 45,
  },
    tokenId: "0.0.47857020",
    serial: 44,
  },
  {
    tokenId: "0.0.47857106",
    serial: 44,
  }
// [...]
let trx = new TransferTransaction()
      .addHbarTransfer(receiverId, -amount)
      .addHbarTransfer(senderId, amount);

nfts.forEach((nft) => {
   trx.addNftTransfer(nft.tokenId, nft.serial, senderId, receiverId);
}); 
```

**Comment by franfernandez20** [comment] 2022-08-20 21:27
![image](https://user-images.githubusercontent.com/23079185/185766466-c2570bf7-c8c4-4baa-9013-adab679b9a75.png)

I attach a capture of the printed transfer before been executed.

**Comment by AdriMsM91** [comment] 2022-08-22 23:26
I have always managed to reproduce the problem, as my partner Fran says, this occurs when more than 1 different Token ID is sent and some of those Token IDs have the same serial.

**Comment by gregscullard** [comment] 2022-08-24 14:52
This may be an issue with the transaction validation (precheck) on Hedera itself rather than an SDK issue. I'll look into it.

**Comment by gregscullard** [comment] 2022-08-24 15:06
@danielakhterov 
Ok, so this looks like Hedera is behaving as expected, when multiple serial numbers for the same token are transferred, they should be included in the same `TokenTransferList`

TokenTransferList should include repeat NftTransfer, one for each serial.
NftTransfer is sender, receiver and serial (+ approval optionally)

So instead of transfer
{tokenId1, [{from, to, serial1}]
{tokenId1, [{from, to, serial2}]

the transaction should be setup as follows
{tokenId1, [{from, to, serial1}, [{from, to, serial2}]

The repeated tokenId error is because there are two or more TokenTransferList with the same TokenId.

https://github.com/hashgraph/hedera-protobufs/blob/main/services/basic_types.proto

**Comment by danielakhterov** [comment] 2022-08-25 18:26
@gregscullard thanks for looking into this. We do merge the token transfers already, but perhaps we're not merging the NFT transfers and/or we're incorrectly merging when the `tokenId` is within a `NftId`. I haven't had the chance to look into this further as I was focusing on the #1152 , but I will try and get this fixed before the upcoming release.

**Closed** 2022-08-29 17:43 UTC
Labels: bug

**Comment by danielakhterov** [comment] 2022-08-29 21:01
Hey, just wanted to mention this was a great find. We did in fact have a bug in the SDK when it came to multiple NFT IDs were added which our test didn't catch as only a couple NFTs. I was able to reproduce this issue and I believe it's fixed. Will be released later today.
