### ISSUE TITLE
WebChannel.decodeUnaryResponse - "unexpectedly received no response"

### ISSUE THREAD

**Issue by 3Nigma** [hashgraph/hedera-sdk-js#1047] opened 2022-04-05 10:10 UTC
### Description

Executing a `fileCreate` or a `cryptoGetBalance` grpc service call returns no HTTP response. 

It might be that other `Executable`s are affected.

> Note: We came across this issue while running [our Strato tests base](https://github.com/buidler-labs/hedera-strato-js/blob/c8cb90d33d4df914e263bd05936006c45947a485/test/) against hedera-sdk v2.12.0

### Steps to reproduce

1. Bundle the sdk and deploy it to a webpage
2. In the same JS context, create either a `FileCreateTransaction` or an `AccountBalanceQuery` and try issuing it through the SDK
3. Inspect network operations to see the lacking of responses

### Additional context

![image](https://user-images.githubusercontent.com/210908/161730247-88672f96-2880-420e-9d80-ea74e86eec07.png)

![image](https://user-images.githubusercontent.com/210908/161730326-76c44b29-7a37-4eb9-9212-4ff75d09ac12.png)

### Hedera network

testnet

### Version

2.12.0

### Operating system

Linux

**Comment by danielakhterov** [comment] 2022-04-08 21:51
Hey, I'm not _really_ sure where to begin with this issue, but it seems v2.12.0 had a bunch of silly mistakes which have now been fixed and released in https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.12.1 Can you attempt to rerun the tests using the updated version. If you're still getting errors then further investigation will be needed.

Note: I tried cloning the repo you mentioned above and running the tests, but they seem to pass with 2.7.0, 2.12.0, and 2.12.1. Although maybe I'm just not running tests correct and/or looking at the correct thing. I ran `npm run test:browser` after updating `.env`.

**Comment by teacoat** [comment] 2022-04-11 20:35
I can expand on this - we have encountered this issue heavily when large projects are using HashConnect. I have talked to @gregscullard about it a bit, but it seems as though when the network is under load this error happens.

We have experienced it across all sorts of transactions - SmartContractExecute, TokenAssociate, Transfer, TokenMint, etc.

The weird part is that sometimes the transaction actually goes through, but then you get an error. This leaves us in a strange position.

It is a very large concern for us and many others.

Some screenshots:
![image](https://user-images.githubusercontent.com/3913019/162826896-72cfc146-ea03-47bb-9413-916d56927017.png)
![image](https://user-images.githubusercontent.com/3913019/162826942-71c913e6-afcb-4108-8ffa-dafe3ac0cedc.png)

**Comment by danielakhterov** [comment] 2022-04-11 23:21
Hmm, based on the screenshots above, the error you're getting is correct; as in the content length is 0 in the response, so we did in fact unexpectedly receive no response. Why this is the case I'm not completely sure, but I'm guessing it has to do with `grpc-web.myhbarwallet.com` which uses https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/grpc I don't currently have access to investigate, but I'll work on getting access/figuring out what's going on there. That said, one _possible_ fix is to host your own web proxy, but I know that's not ideal.

**Comment by danielakhterov** [comment] 2022-04-12 01:29
@HGraphPunks Just want to double check, but is this a result of v2.12.0 or in general?

**Comment by teacoat** [comment] 2022-04-12 01:52
@danielakhterov we have been using 2.11.x, but have encountered it in earlier versions as well.

The tricky part is that it happens during .execute(), but the transaction is executed successfully. 

This was the suggested fix, which seems like something that should be wrapped up in the sdk because this problem is only going to happen more and more as the network gets used more:
![image](https://user-images.githubusercontent.com/3913019/162862877-07989c33-7f67-4028-8b9a-e45f7def4f61.png)

**Comment by danielakhterov** [comment] 2022-04-12 02:38
> This was the suggested fix, which seems like something that should be wrapped up in the sdk because this problem is only going to happen more and more as the network gets used more:

This error should realistically never happen. It's likely happening  because there is a bug in the envoy proxy or maybe somewhere else I'm not seeing. Java and Go _to my understanding_ have never failed with such errors which is another reason I think it's an envoy proxy issue.

> Essentially, the network may fail, but the sdk should automatically retry and obfuscate that fact and respond as if no network failure occured.

I don't think classifying this as a `network fail` is correct. HTTP handles the network communication, and that means the request was sent successfully, and the response we got was in fact what the server sent. This is a bug somewhere in either the SDK, grpc-web envoy proxy, or Hedera Services. Since, Java nor Go have ever failed (again to my understanding) with a response of length 0 I don't think its Hedera Services that is the issue, and from the screenshots you sent the server did respond with a content of length 0 which makes me think it's not the SDK that contains the bug either. That last thing there is a web proxy bug and I don't think this is something the SDK should be taking care of. The other thing to note, is that Hedera has not officially supported grpc-web, so the current web proxies are there as conveniences, but officially our position is that users should host their own proxies.

**Comment by VallVall** [comment] 2022-04-13 13:56
@3Nigma @HGraphPunks

Install 2.8.0 version - it works, before update of version - delete node_modules folder

**Comment by danielakhterov** [comment] 2022-04-13 20:56
If downgrading to version 2.8.0 solves this issue then I think that confirms this is an SDK issue; downgrading shouldn't be able to solve this issue though unless I'm not seeing something.

**Comment by teacoat** [comment] 2022-04-18 16:05
No matter what I do, I cannot handle this error. 

![image](https://user-images.githubusercontent.com/3913019/163836765-2173d4de-84c7-4e5f-b870-8b7a0c132017.png)

None of these catch's work

![image](https://user-images.githubusercontent.com/3913019/163836831-39e9cd25-553f-4b97-95e2-33ca6bc23d9b.png)

I'm at a loss how to handle this.

**Comment by teacoat** [comment] 2022-04-18 18:35
I can confirm it is still happening in 2.8.0

**Comment by danielakhterov** [comment] 2022-04-18 22:30
Okay, so I think this may have been multiple issues happening at the same time which made it difficult to determine what was the issue. However, I created a basic vue app using `vue create vue-example`, then `pnpm add @hashgraph/sdk`. Running
```javascript
  setup() {
    new AccountBalanceQuery().setAccountId("0.0.3").execute(Client.forTestnet()).then((value) => console.log(value));
  }
```
**failed**. However, the reason it failed was obvious when reading the network. 
![image](https://user-images.githubusercontent.com/36461294/163881794-f35a8c1f-84bb-414e-9fe6-887f2b1b4b02.png)
As you can see the URL contains `HashgraphProto.proto` which is a search/replace mistake. This issue was fixed here: 50dad309e413e69b8fa24170c55bf812f04caed4 However, said that your original screenshot https://user-images.githubusercontent.com/3913019/162826942-71c913e6-afcb-4108-8ffa-dafe3ac0cedc.png shows the correct URL. So, what I think is happening is that yes v2.11.3-v2.12.1 were incorrectly constructing the URL, and at the same time the proxy was more occasionally than not returning no content for other requests which is why you experienced it with other versions. Released fixed: https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.13.0

**Comment by teacoat** [comment] 2022-04-19 00:18
@danielakhterov I think your fix will indeed fix the original issue of this ticket and that other ticket I opened about the account balance transaction not working. But I did just hit the same issue again using 2.13.0.

However, I think there is another situation here that may make sense to open a new ticket for, or we can just continue on this one.

Basically, I am still hitting this (BUG) thing, and the error seems to not be bubbling up at all.

![image](https://user-images.githubusercontent.com/3913019/163896336-040a7a39-87e8-41e7-9964-ecbc480e7678.png)

I am wrapping the execute call in all the catch's I can but its just not triggering them, it's like it just stops.

![image](https://user-images.githubusercontent.com/3913019/163896399-9589a0f2-f450-4872-86de-f4a2b6b3c20d.png)

If I were able to catch this error I could do _something_ about it, but as of right now this error seems to just killl the call.

**Comment by danielakhterov** [comment] 2022-04-19 01:07
Reopening this issue does make sense for this.

**Comment by danielakhterov** [comment] 2022-04-27 00:28
Fixed: https://github.com/hashgraph/hedera-sdk-js/commit/bc2592b497d97c6cbccee5a458665fb278933d73
Can confirm our browser tests were now able to catch the original error of having `HashgraphProto` in the URL.

**Closed by danielakhterov** 2022-04-27 00:28 UTC
Labels: bug

**Comment by teacoat** [comment] 2022-04-27 01:30
<3

**Comment by cacampbell** [comment] 2022-08-10 18:31
> +1
> 
> This is an issue that has happened on almost every launch we have done on Turtle Moon Launchpad. The bug is impairing the user experience for many who thought they'd be able to mint, but the hanging stops them from executing the transaction and then the NFTs sell out before they can try again.

The MyHbarWallet proxy is not suitable for production! It will fall down and die if you yell at it.

**Comment by danielakhterov** [comment] 2022-08-10 18:55
Linking issue from services: https://github.com/hashgraph/hedera-services/issues/3770
