### ISSUE TITLE
StatusError: DUPLICATE_TRANSACTION

### ISSUE THREAD

**Issue by Steven-Yulong-Yan** [hashgraph/hedera-sdk-js#1401] opened 2023-01-19 12:55 UTC
### Description

Although this was marked resolved some time ago, I believe I am having the same problem with https://github.com/hashgraph/hedera-sdk-js/issues/253.

### Steps to reproduce

Running a batch of SDK transactions on AWS Lambda with reserved currency at 1.

### Additional context

2023-01-18T01:18:34.421+10:00
{
    "name": "StatusError",
    "status": "DUPLICATE_TRANSACTION",
    "transactionId": "0.0.47769414@1673968701.208663621",
    "message": "transaction 0.0.47769414@1673968701.208663621 failed precheck with status DUPLICATE_TRANSACTION",
    "contractFunctionResult": null
}

### Hedera network

testnet

### Version

2.17.0

### Operating system

macOS

**Comment by ochikov** [comment] 2023-01-19 13:06
Hello @Steven-Yulong-Yan, can you confirm that you are using the current latest version, or the reported one is right: 2.17.0?

**Comment by Steven-Yulong-Yan** [comment] 2023-01-19 13:25
@ochikov I'm using the reported ^2.17.0, did you think the current version could fix it?

**Comment by ochikov** [comment] 2023-01-19 14:12
@Steven-Yulong-Yan You can try, but if you provide us with a more detailed example of your setup, we can investigate and return to you what can be done and if this is still an issue.

**Comment by AdriMsM91** [comment] 2023-01-19 22:32
Hello good night,

Its happening to me also with `TransferTransaction `in Batches sending NFTs. In my case It has been with the SDK version `2.18.6` 

Regards

**Comment by ochikov** [comment] 2023-01-20 08:39
@AdriMsM91 can you provide an example so we can reproduce it?

**Comment by AdriMsM91** [comment] 2023-01-20 10:40
My code is directly executed in FrontEnd.

```js
 const txResponse = new TransferTransaction()
      .setMaxTransactionFee(new Hbar(maxFee))
      .addHbarTransfer(originAccountId, hbarAmount.negated()) 
      .addHbarTransfer(targetAccountId, hbarAmount); 
  const txSubmit = await txResponse.execute(client);
  const receipt = await txSubmit.getReceipt(client);
 ```

```js
let txTransfer = new TransferTransaction()
      .setMaxTransactionFee(new Hbar(maxFee))
      .setTransactionMemo(memo);
    accounts.forEach((receiver) => {
      txTransfer.addNftTransfer(
        receiver.tokenId,
        receiver.serialNumber,
        receiver.originAccount,
        receiver.receiverAccount
      );
    });
    const txSubmit = await txTransfer.execute(client);
    const receipt = await txSubmit .getReceipt(cliient)

**Comment by petreze** [comment] 2023-01-23 09:35
@AdriMsM91 
Are you experiencing this behaviour on `testnet` as @Steven-Yulong-Yan described or on mainnet?

**Comment by AdriMsM91** [comment] 2023-01-23 09:41
Hello @petreze on Mainnet.

**Comment by ochikov** [comment] 2023-01-23 09:46
@AdriMsM91 the first code that you posted with transferring Hbar amount, I was able to test the same scenario on React Fe. I've got 1000 transactions and I cannot reproduce the duplicate transaction. I am hitting a node that is not working, but the SDK is retrying and processing the transaction to another node as seen in the logs below. What about the `accounts.forEach((receiver) => {` ? Maybe we've got the same account twice in the list of the accounts? I am using 2.19.2 version. 
```
Start
App.js:26 11:32:03
App.js:37 Start 0
App.js:46 The transfer receipt for iteration 0 is SUCCESS
App.js:37 Start 1
App.js:46 The transfer receipt for iteration 1 is SUCCESS
App.js:37 Start 2
App.js:46 The transfer receipt for iteration 2 is SUCCESS
App.js:37 Start 3
WebChannel.js:59          POST https://node03.swirldslabs.com/proto.CryptoService/cryptoTransfer 503
(anonymous) @ WebChannel.js:59
rpcCall @ service.js:94
executor @ index.js:44
asPromise @ index.js:28
rpcCall @ service.js:85
cryptoTransfer @ proto.js:1
_execute @ TransferTransaction.js:705
execute @ Executable.js:626
await in execute (async)
test @ App.js:39
await in test (async)
onClick @ App.js:106
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
App.js:46 The transfer receipt for iteration 3 is SUCCESS
App.js:37 Start 4
App.js:46 The transfer receipt for iteration 4 is SUCCESS
App.js:37 Start 5
App.js:46 The transfer receipt for iteration 5 is SUCCESS
App.js:37 Start 6
App.js:46 The transfer receipt for iteration 6 is SUCCESS
App.js:37 Start 7
App.js:46 The transfer receipt for iteration 7 is SUCCESS
App.js:37 Start 8
App.js:46 The transfer receipt for iteration 8 is SUCCESS
App.js:37 Start 9
App.js:46 The transfer receipt for iteration 9 is SUCCESS
App.js:37 Start 10
App.js:46 The transfer receipt for iteration 10 is SUCCESS
App.js:37 Start 11
App.js:46 The transfer receipt for iteration 11 is SUCCESS
App.js:37 Start 12
App.js:46 The transfer receipt for iteration 12 is SUCCESS
App.js:37 Start 13
App.js:46 The transfer receipt for iteration 13 is SUCCESS
App.js:37 Start 14
App.js:46 The transfer receipt for iteration 14 is SUCCESS
App.js:37 Start 15
App.js:46 The transfer receipt for iteration 15 is SUCCESS
App.js:37 Start 16
App.js:46 The transfer receipt for iteration 16 is SUCCESS
App.js:37 Start 17
App.js:46 The transfer receipt for iteration 17 is SUCCESS
App.js:37 Start 18
App.js:46 The transfer receipt for iteration 18 is SUCCESS
App.js:37 Start 19
App.js:46 The transfer receipt for iteration 19 is SUCCESS
App.js:37 Start 20
App.js:46 The transfer receipt for iteration 20 is SUCCESS
App.js:37 Start 21
App.js:46 The transfer receipt for iteration 21 is SUCCESS
App.js:37 Start 22
App.js:46 The transfer receipt for iteration 22 is SUCCESS
App.js:37 Start 23
App.js:46 The transfer receipt for iteration 23 is SUCCESS
App.js:37 Start 24
App.js:46 The transfer receipt for iteration 24 is SUCCESS
App.js:37 Start 25
App.js:46 The transfer receipt for iteration 25 is SUCCESS
App.js:37 Start 26
App.js:46 The transfer receipt for iteration 26 is SUCCESS
App.js:37 Start 27
WebChannel.js:59          POST https://node04.swirldslabs.com/proto.CryptoService/cryptoTransfer 503
(anonymous) @ WebChannel.js:59
rpcCall @ service.js:94
executor @ index.js:44
asPromise @ index.js:28
rpcCall @ service.js:85
cryptoTransfer @ proto.js:1
_execute @ TransferTransaction.js:705
execute @ Executable.js:626
await in execute (async)
test @ App.js:39
await in test (async)
onClick @ App.js:106
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
App.js:46 The transfer receipt for iteration 27 is SUCCESS
App.js:37 Start 28
App.js:46 The transfer receipt for iteration 28 is SUCCESS
App.js:37 Start 29
App.js:46 The transfer receipt for iteration 29 is SUCCESS
App.js:37 Start 30
App.js:46 The transfer receipt for iteration 30 is SUCCESS
App.js:37 Start 31
App.js:46 The transfer receipt for iteration 31 is SUCCESS
App.js:37 Start 32
App.js:46 The transfer receipt for iteration 32 is SUCCESS
App.js:37 Start 33
App.js:46 The transfer receipt for iteration 33 is SUCCESS
App.js:37 Start 34
App.js:46 The transfer receipt for iteration 34 is SUCCESS
App.js:37 Start 35
App.js:46 The transfer receipt for iteration 35 is SUCCESS
App.js:37 Start 36
WebChannel.js:59          POST https://node03.swirldslabs.com/proto.CryptoService/cryptoTransfer 503
(anonymous) @ WebChannel.js:59
rpcCall @ service.js:94
executor @ index.js:44
asPromise @ index.js:28
rpcCall @ service.js:85
cryptoTransfer @ proto.js:1
_execute @ TransferTransaction.js:705
execute @ Executable.js:626
await in execute (async)
test @ App.js:39
await in test (async)
onClick @ App.js:106
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
App.js:46 The transfer receipt for iteration 36 is SUCCESS
App.js:37 Start 37
App.js:46 The transfer receipt for iteration 37 is SUCCESS
App.js:37 Start 38
App.js:46 The transfer receipt for iteration 38 is SUCCESS
App.js:37 Start 39
App.js:46 The transfer receipt for iteration 39 is SUCCESS
App.js:37 Start 40
App.js:46 The transfer receipt for iteration 40 is SUCCESS
App.js:37 Start 41
App.js:46 The transfer receipt for iteration 41 is SUCCESS
App.js:37 Start 42
App.js:46 The transfer receipt for iteration 42 is SUCCESS
App.js:37 Start 43
App.js:46 The transfer receipt for iteration 43 is SUCCESS
App.js:37 Start 44
App.js:46 The transfer receipt for iteration 44 is SUCCESS
App.js:37 Start 45
App.js:46 The transfer receipt for iteration 45 is SUCCESS
App.js:37 Start 46
App.js:46 The transfer receipt for iteration 46 is SUCCESS
App.js:37 Start 47
App.js:46 The transfer receipt for iteration 47 is SUCCESS
App.js:37 Start 48
App.js:46 The transfer receipt for iteration 48 is SUCCESS
App.js:37 Start 49
App.js:46 The transfer receipt for iteration 49 is SUCCESS
App.js:37 Start 50
App.js:46 The transfer receipt for iteration 50 is SUCCESS
App.js:37 Start 51
App.js:46 The transfer receipt for iteration 51 is SUCCESS
App.js:37 Start 52
App.js:46 The transfer receipt for iteration 52 is SUCCESS
App.js:37 Start 53
App.js:46 The transfer receipt for iteration 53 is SUCCESS
App.js:37 Start 54
App.js:46 The transfer receipt for iteration 54 is SUCCESS
App.js:37 Start 55
WebChannel.js:59          POST https://node03.swirldslabs.com/proto.CryptoService/cryptoTransfer 503
(anonymous) @ WebChannel.js:59
rpcCall @ service.js:94
executor @ index.js:44
asPromise @ index.js:28
rpcCall @ service.js:85
cryptoTransfer @ proto.js:1
_execute @ TransferTransaction.js:705
execute @ Executable.js:626
await in execute (async)
test @ App.js:39
await in test (async)
onClick @ App.js:106
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
App.js:46 The transfer receipt for iteration 55 is SUCCESS
App.js:37 Start 56
```

**Comment by AdriMsM91** [comment] 2023-01-23 09:55
Hello @ochikov 

I see one difference there, which shouldn't matter at all... but who knows... you're executing every Transaction, saving the receipts and doing later one Promise.allSettled() , we were executing:

1. One Transfer Transaction with 10 NFTs inside (Batch of 10 Metadatas). --> Get Receipt --> Once the Receipt is good, we were doing.. (2.)
2. One Transfer Transaction Hbar (The code I posted above) --> Get Receipt --> Once the receipt is good, we go back to point (1.)

Our Platform probably sent around 70k NFTs in BulkSender (NFTs sent + Fees with Hbar Transfer in 2 differents Trx) and we got the Error Reported only 2 Times by 2 differents users.

**Comment by ochikov** [comment] 2023-01-23 10:14
@AdriMsM91 I am doing a Transfer Transaction and getting the receipt. What is `Promise.allSettled()` ? 
I will try to prepare example with your usage, but you can help us if you have ready to use code?

**Comment by AdriMsM91** [comment] 2023-01-23 10:22
Oh nvm @ochikov I looked at the code wrongly, basically Promise.allSettled() what It does is throw async every petition and resolve. I thought you were saving the receipts and then at the end doing that, my bad.

I have ready the code, but the code has 4 differents layers, with methods...etc , so adapt all of that for your usage its gonna take to me a while...

**Comment by ochikov** [comment] 2023-01-25 15:38
@AdriMsM91 Do you have the chance for the code? I cannot reproduce it at all.

**Comment by AdriMsM91** [comment] 2023-01-25 16:09
> @AdriMsM91 Do you have the chance for the code? I cannot reproduce it at all.

Not really @ochikov I'm sorry, we have developed the first fully automated Launchpad yesterday, so really busy, I'll try to get that ready for tomorrow.

**Comment by ochikov** [comment] 2023-02-01 20:33
@AdriMsM91 do you experience the same behaviour with the latest beta version?

**Comment by AdriMsM91** [comment] 2023-02-01 20:56
Hello @ochikov I can't be doing again the tests and less when this has never happened to us on Testnet. It means I would need to spend a lot of Hbars to test in Mainnet since It doesn't happen in the iteration 500 ot 1000, can be in the 8,000 or might in the 15,000 is totally ramdom. In Testnet with more than I don't know... 250k Transactions never happened to us.

**Comment by AdriMsM91** [comment] 2023-02-09 16:53
@ochikov Yes, If It happens again I'll reopen. Thanks.

**Comment by ochikov** [comment] 2023-02-10 11:19
@Steven-Yulong-Yan Can we close the issue?

**Comment by Steven-Yulong-Yan** [comment] 2023-02-10 12:16
@ochikov Thanks for asking, if it comes up again I'll let you know

**Closed** 2023-02-10 12:16 UTC
Labels: bug
