### ISSUE TITLE
CONTRACT_REVERT_EXECUTED error does not return a valid account ID in the transaction ID - makes debugging contracts difficult

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#1096] opened 2022-04-26 17:28 UTC
### Description

Debugging smart contracts on Hedera is notoriously difficult compared to other ecosystems. 

One example of that is that when a contract reverts, it's not straight forward to get a transaction record or query the transaction ID returned in the error. That is because the account ID portion in the transaction ID returned is not valid:

`receipt for transaction 0.0.0@1650655159.389599287 contained error status CONTRACT_REVERT_EXECUTED`

The SDK should return a useful transaction ID. 

### Steps to reproduce

[test.zip](https://github.com/hashgraph/hedera-sdk-js/files/8565542/test.zip)

The zip attached includes:
- test.js
- test.sol
- and test_sol_xx...bin

Running the attached test.js results in the error included in the description above. This issue is also true for any smart contract that reverts.

### Hedera network

testnet

### Version

v0.25

### Operating system

Windows

**Comment by danielakhterov** [comment] 2022-04-27 00:17
Which SDK version are you using?
This seems to be a duplicate of https://github.com/hashgraph/hedera-sdk-js/issues/1008 which as been resolved.

**Closed** 2022-04-27 00:19 UTC
Labels: bug
