### ISSUE TITLE
AccountAllowanceDeleteTransaction.deleteAllTokenNftAllowances()

### ISSUE THREAD

**Issue by AdriMsM91** [hashgraph/hedera-sdk-js#1427] opened 2023-01-31 12:46 UTC
### Description

Good morning,

First of all I'd like to report that actually the documentation is wrong. As you can see in the following link: https://docs.hedera.com/hedera/docs/sdks/cryptocurrency/adjust-an-allowance , first of all It sais Method: `deleteAllNftAllowances `(Which doesn't exist) and then later in the example uses another one different (`deleteAllTokenNftAllowances`)

After that I've trying many differents things following the example: 
```js
const transaction = new AccountAllowanceDeleteTransaction()
    .deleteAllTokenNftAllowances(nftId , ownerAccountId);
```
    
So... looking at this example, I'm assuming all what I need to pass in nftId is a TokenId (Since in the SDK It sais nftId: String || NftId) (What would be logical) , but doing that I'm getting this error:

```js
error TypeError: Cannot read properties of undefined (reading 'length')
    at Function.fromString (long.js?1aca:221:1)
    at NftId.fromString (NftId.js?1567:60:24)
```

So the only way to make it works is using the Class NftId, where you need to pass one SerialNumber and It doesn't make sense. Also I'm removing the Allowance of an specific NFT, but It is letting me send anyways. 

I want to revoke all the Allowance permissions from the TokenId and I don't want to be specifying serialNumbers (Limit of 20), revoke that just like I can put all in:

```js
new AccountAllowanceApproveTransaction().approveTokenNftAllowanceAllSerials(
         tokenId,
         client.operatorAccountId,
         spenderAccountId
       )
```
So... I'd like to be able to remove them all as well. Also... as I can see there isn't any EndPoint in MirrorNode for NFTs Allowance and either I can see by any way which TokenAllowance has been setted , If I approve with all Serial Number (approveTokenNftAllowanceAllSerials) . 

The follow code is an example how I got `SUCCESS `to return the transaction, but even removing access to that Serial 10, from the account that had permissions, I was able to send it.

```js
 const nftId = new NftId(new TokenId(0, 0, 3065157), 10);
 ```

### Steps to reproduce

```js
const tokenId = '0.0.3065157'
    const accountAllowanceDeleteTx =
      new AccountAllowanceDeleteTransaction().deleteAllTokenNftAllowances(
        tokenId,
        client.operatorAccountId
      );
   const txResponse = await accountAllowanceDeleteTx.execute(client);
   const receipt = await txResponse.getReceipt(client);
        

### Additional context

_No response_

### Hedera network

testnet

### Version

2.19.1

### Operating system

Windows

**Comment by petreze** [comment] 2023-02-01 13:42
Hey @AdriMsM91 
I've created a PR in regards to the documentation inconsistency. Now I'm starting to investigate the issue itself

**Comment by ed-marquez** [comment] 2023-02-02 15:23
[This example](https://github.com/ed-marquez/hedera-example-allowances-sdk/blob/7fe7996bd755f343659bfe2fc3643e8708a19e54/index_nft.js#L71) calls [this function](https://github.com/ed-marquez/hedera-example-allowances-sdk/blob/7fe7996bd755f343659bfe2fc3643e8708a19e54/utils/allowanceApprovals.js#L35), which successfully deletes NFT allowances using the SDK. 

Note that in this example an NftId object is passed to 
`AccountAllowanceDeleteTransaction()..deleteAllTokenNftAllowances(NftId, owner)`

Based on the ERC standard that the SDK follows (according to Michael T.), users can't:
- approve allowance for all NFTs, then remove allowance for individual NFTs
- approve allowance for individual NFTs, then remove allowance for all NFTs

Hope this helps.

**Comment by petreze** [comment] 2023-02-02 15:46
@AdriMsM91 
Yes, basically `new AccountAllowanceDeleteTransaction().deleteAllTokenNftAllowances(nftId , ownerAccountId)` expects the type of `nftId` parameter to be a `NftId` object or a string in `NftId` format not in `TokenId` format

**Comment by AdriMsM91** [comment] 2023-02-02 15:52
Ey @petreze good afternoon!

I've talking with @ed-marquez via Discord. So there is a problem, If I allow 10k NFTs with:

```js
 const transaction = new AccountAllowanceApproveTransaction()
      .approveTokenNftAllowanceAllSerials(
        tokenId,
        client.operatorAccountId,
        spenderAccountId
      )
      .setMaxTransactionFee(new Hbar(maxFee));
    const txResponse = await transaction.execute(client);
```

Basically I'm not gonna be able to delete de Allowance, right now looks like there isn't any way and looks like the problem is coming from the implementation in Hedera Services, that is, the Hedera API which is more base. So @ed-marquez is consulting it with the engineers at Swirlds Labs. 

Hopefully @ed-marquez can give us more info soon!

**Comment by ed-marquez** [comment] 2023-02-02 19:11
**Bottleneck**: When using the SDKs, a user can approve allowances for all serials of an NFT collection with a single tx, but can't remove allowances for all serials with a single tx.
So right now, the only **workaround** I can think of with the SDK is to approve allowances individually for each serial and remove the allowances for each serial for NFT collections. These guys are dealing with ~10,000 serials, for multiple collections, so that's not an ideal solution.

**Next Step:**
@petreze @AdriMsM91 
I was checking the EIP for ERC-721 (https://eips.ethereum.org/EIPS/eip-721#:~:text=function%20setApprovalForAll(address%20_operator%2C%20bool%20_approved)%20external%3B) and looks like the variable `_approved` can be set to `false` in the `setApprovalForAll` function to revoke approval for all NFTs.

The services team also confirmed that, in HAPI, when the `NftAllowance.approved_for_all = false in CryptoApproveAllowanceTransactionBody`, we revoke the token for the spender for which we have previously allocated `approve_for_all` allowance.

So it looks that the SDK is not matching this HAPI functionality. 
Currently, the only way to remove NFT allowances with the SDK is to use `AccountAllowanceDeleteTransaction().deleteAllTokenNftAllowances(NftId, owner)`, which as we mentioned above, only accepts an NftId object. 
Given that the ability to revoke an allowance for all NFTs is available in HAPI, **the SDK should provide a way to revoke an allowance for all serials in an NFT collection in a single transaction.**

**Comment by petreze** [comment] 2023-02-03 08:34
@ed-marquez 
I see, so this will be the next step to implement the allowance removal of all serials for a single NFT.
Furthermore, I can verify that the points you have mentioned above are correct in regards to the SDK as well:

_approve allowance for all NFTs, then remove allowance for individual NFTs
approve allowance for individual NFTs, then remove allowance for all NFTs_

I tried approving allowance for all serials (`1,2,3`) of a NFT with `approveTokenNftAllowanceAllSerials` and then deleting the allowance for serial `1` did **not** stop me from sending it successfully.
(which is basically what @AdriMsM91 described with: _Also I'm removing the Allowance of an specific NFT, but It is letting me send anyways._)
When approving allowance for serials one by one with `approveTokenNftAllowance`, then deleting the allowance for serial `1`, this prevented the sending of this exact serial with `SPENDER_DOES_NOT_HAVE_ALLOWANCE`

Therefore, a `deleteTokenNftAllowanceAllSerials()` method will be implemented according to the plan

**Comment by ed-marquez** [comment] 2023-02-03 15:35
Excellent - thank you @petreze ! 

Ok, so just to summarize: 
approve allowance for **all** serials ==> delete allowance for **all** serials 
[✅works in ERC-721 and HAPI, **will be added to SDKs**]

approve allowance for **all** serials ==> delete allowance for **individual** serials 
[❌not supported by ERC-721, HAPI, or SDK]

approve allowance for **individual** serials ==> delete allowance for the same **individual** serials (if not transferred)
[✅works in ERC-721, HAPI, and SDKs]

approve allowance for **individual** serials ==> delete allowance for **all** serials 
[❌not supported by ERC-721, HAPI, or SDK]

Let me know if the above is not correct.
Have a good weekend.

**Comment by petreze** [comment] 2023-02-03 15:50
@ed-marquez 
Yes, exactly, all correct !
I've also created an [issue](https://github.com/hashgraph/hedera-services/issues/4862) in services regarding the 2 not supported ❌ scenarios to add some type of indication to the user that this is not allowed behaviour (new response code or using an already existing one)

Because now as @AdriMsM91 pointed out and I've tested it, you can still perform one of those setups and the `AccountAllowanceDeleteTransaction` will be executed and the receipt's status will be `SUCCESS` but despite that, nothing will change and this is misleading. And on top of that, the nft can still be transferred from the allowed account. So my suggestion was to somehow handle those 2 potential outcomes as they are not that well documented as concepts

**Comment by SimiHunjan** [comment] 2023-02-03 16:02
@petreze can we make sure to review the other SDKs and make sure `deleteTokenNftAllowanceAllSerials()` exists and if not we need to create issues to add that to the other SDKs in a future sprint.

**Comment by petreze** [comment] 2023-02-03 16:06
@SimiHunjan 
Yup of course, will do that !

**Comment by ed-marquez** [comment] 2023-02-03 16:08
Agreed @petreze - services should provide appropriate errors for the 2 cases that are not supported. 
I also added a [doc issue](https://github.com/hashgraph/hedera-docs/issues/258) to document the information above in the relevant pages. Hopefully, that'll cover all our bases. 
Thank you again!

**Comment by justynspooner** [comment] 2023-02-13 23:15
@AdriMsM91 mentioned a very important issue related to approving/revoking allowances:

> Also... as I can see there isn't any EndPoint in MirrorNode for NFTs Allowance and either I can see by any way which TokenAllowance has been setted , If I approve with all Serial Number (approveTokenNftAllowanceAllSerials) .

We can't find this either. There doesn't seem to be a way to get NFTs that have been approved by the `approveTokenNftAllowanceAllSerials` transaction for an account.

There are two open tickets below which would be great to address along with these allowance delete transaction fixes as they allow us to check which NFTs are allowed/not allowed to be spent by a Spender.

Get the approved allowance NFTs set by the Owner:
https://github.com/hashgraph/hedera-mirror-node/issues/3245

Get the approved allowance NFTs controlled by a Spender:
https://github.com/hashgraph/hedera-mirror-node/issues/4348

**Closed** 2023-02-14 13:59 UTC
Labels: bug
