### ISSUE TITLE
Fail with gRPC Proxy executing Trx FrontEnd and don't redirect to another one

### ISSUE THREAD

**Issue by AdriMsM91** [hashgraph/hedera-sdk-js#1524] opened 2023-03-25 00:38 UTC
### Description

After **2555 NFTs minted in Mainnet** (255 Batches and each batch is based on: **Transaction sending Hbar + Transactions of Minting NFTs**, in total **510 Transactions** has been executed), directly from the browser (It means the Transaction don't get executed in BackEnd), It gets executed directly in the FrontEnd via gRPC + Proxies, we got a 503 in the Node04 of Swirlds (We have a work around to retry 3 times to get the receipt, although I thought you guys fixed this last time we opened the issue. As far as I thought  the SDK would directly rebalance  to an operative Proxie & Node, but as I can see It's not working as expected. After my 3 retries the execution is cut by throwing an Error.

Also after this, we got the same Error than we reported 2-3 months ago, that you guys weren't able to reproduce it. 
`Transaction must have been frozen before calculating the hash will be stable, try callen freeze`

This is something critical for Kabila App, since we're providing this services and our customers are having troubles with it.

![image](https://user-images.githubusercontent.com/59306428/227668276-9f460eea-c05f-45aa-b107-cb9076bca0cc.png)
![image](https://user-images.githubusercontent.com/59306428/227668300-9898872e-9e7b-413b-8e74-6e13ac58fd50.png)

### Steps to reproduce

 ```js
 let mintTx = new TokenMintTransaction()
     .setMaxTransactionFee(new Hbar(maxFee))
     .setTokenId(tokenId);
     .setMetadata(metadata);
    mintTx.freezeWith(client);
    const mintTxSign = await mintTx.sign(supplyKey);
    const mintTxResponse =  await mintTxSign.execute(client);
    const receipt = await mintTxResponse.getReceipt(client);
     
    let txTransfer = new TransferTransaction()
      .setMaxTransactionFee(new Hbar(maxFee))
      .setTransactionMemo(memo)
      .addHbarTransfer(account1, hbarAmount.negated()) 
      .addHbarTransfer(account2, hbarAmount);
    const mintTxResponse = await txTransfer.execute(client);
    const receipt = await txSubmit.getReceipt(client);
 ```

### Hedera network

mainnet

### Version

2.20.0

### Operating system

Windows

**Comment by ochikov** [comment] 2023-03-27 10:56
@AdriMsM91 regarding the retries, I cannot see any problem. Did you lock the nodes on your side?

**Comment by ochikov** [comment] 2023-03-27 14:32
@AdriMsM91 I mean by setting the setter: 
``` 
          .setNodeAccountIds([
            new AccountId(7),
            new AccountId(8),
            new AccountId(9),
          ])
``` 
for example with specified nodes?

**Comment by AdriMsM91** [comment] 2023-03-27 14:33
Nop, 

  **let client = Client.forNetwork(network);**

**Comment by ochikov** [comment] 2023-03-27 14:35
Perfect, so from my applied screenshots, you can see that it works as expected. I am still trying to identify why 
```
Transaction must have been frozen before calculating the hash will be stable, try callen freeze
```
is happening. Because when it occurs, all transactions are failing. I still cannot reproduce it without closing the lid of the laptop. It's super strange behavior.

**Comment by AdriMsM91** [comment] 2023-03-27 15:13
It usually works as expected, but some times It doesn't and I don't know why.

**Comment by ochikov** [comment] 2023-03-27 20:26
@AdriMsM91 is there any chance when you are waiting for the NFTs to be minted and for the transfer transaction, something to kill the process of the SDK? What time is needed for the execution of the process?

**Comment by ochikov** [comment] 2023-03-30 13:46
@AdriMsM91 I cannot catch any problem related with the healthy/unhealthy nodes.

**Comment by AdriMsM91** [comment] 2023-03-31 23:44
Yeah it's super hard to catch up, only happens when you mint really big amounts + big amounts of Hbar Transfer in Mainnet in the FrontEnd directly, without using Node.js for anything related about executing transactions.  :(

**Comment by AdriMsM91** [comment] 2023-04-02 20:43
@ochikov Again today another client with the same problem. 
![image](https://user-images.githubusercontent.com/59306428/229378003-b9399f0d-adb3-43bd-80f7-22d76926e234.png)

**Comment by ochikov** [comment] 2023-04-10 08:38
@AdriMsM91 I understand, but the behavior is really hard to be reproduced. I cannot propose any solution right now.

**Comment by ochikov** [comment] 2023-04-26 06:08
@AdriMsM91 Hello, I will close the issue.

**Comment by ochikov** [comment] 2023-05-22 14:43
Version 2.26.0-beta.2 should fix the issue.

**Closed** 2023-05-26 05:31 UTC
Labels: bug
