### ISSUE TITLE
The SDK returns `FAILED_INVALID` when querying a transactions receipt but the transaction is actually successful

### ISSUE THREAD

**Issue by pathornteng** [hashgraph/hedera-sdk-js#1519] opened 2023-03-21 07:57 UTC
### Description

Currently, there is a chance ,when querying a transaction receipt, that the application will get an error such as `FAILED_INVALID` or other errors while the actual transaction is successful. I have seen a number of people reporting this issue but I don't know how to reproduce it myself. This is quite a serious bug as the application considers transaction receipts as the confirmation of the transactions. Returning incorrect result causes the application to resubmit the transaction or trying to replay the action.

Could someone one the team investigate this issue? It mostly occurs when the users submit a bunch of transaction to the network at the same time.

### Steps to reproduce

Do some performance test by submitting a bunch of transaction to the network and recheck all the transaction receipts if they all match the result on the network

### Hedera network

mainnet, testnet, previewnet

### Version

2.22.0

### Operating system

None

**Comment by ochikov** [comment] 2023-03-21 08:04
Hello @pathornteng, I will try to reproduce it. Can you give more information as to where it mainly occurs? Testnet/Mainnet? I can see that you reported it on the three networks, but maybe it happens frequently on one of them?
I will try with the transfer transaction.

**Comment by pathornteng** [comment] 2023-03-21 08:15
Hi @ochikov, I think all have the same problems. I would try to reproduce it on testnet. Thanks for taking a look at the issue.

**Comment by stoqnkpL** [comment] 2023-03-21 08:15
@pathornteng if you can give us an example transaction id reproducing the issue that can also be helpful

**Comment by pathornteng** [comment] 2023-03-21 08:15
Let's try the minting token transactions. it's the one that get reported

**Comment by pathornteng** [comment] 2023-03-21 08:17
This is the transaction that get reported https://hashscan.io/mainnet/transaction/1679355003.891404219?tid=0.0.1437125-1679354992-717618538

**Comment by ochikov** [comment] 2023-03-21 09:42
@pathornteng I've created a hundred transfer transactions on the Mainnet and get the receipt through `TransactionReceiptQuery`. They all are executed without any error. I will continue to debug.

**Comment by pathornteng** [comment] 2023-03-21 09:56
@ochikov is it possible to submit minting NFT to multiple servers and one of them returns error and the others are able to process the transaction later? The problem is likely to happen with intensive transactions like minting / create tokens more than a simple transfer transaction.

**Comment by ochikov** [comment] 2023-03-21 11:01
@pathornteng I will try NFT minting on the testnet. The workflow is that SDK is trying to submit a transaction to a particular node. If the node is marked as unhealthy (cannot process the transaction) the SDK has a default of 10 retries to submit that transaction. There is no such thing as mint NFT "to multiple servers". Can you elaborate more on that?

**Comment by pathornteng** [comment] 2023-03-21 11:10
@ochikov From what I understand, we can submit a single transaction to multiple nodes at the same time. Not sure if our SDK can do it. But at the network level, consensus nodes will be able to reconcile the transactions and process it.

**Comment by ochikov** [comment] 2023-03-21 13:01
@pathornteng I've created a TokenCreateTransaction, then a hundred TokenMintTransaction mint transactions, then a token associate and token transfer transactions. I still cannot reproduce it.

**Comment by pathornteng** [comment] 2023-03-22 09:18
Ok thank you all, let's close the issue for now. I will reopen a new one if I am able to reproduce this.

**Closed** 2023-03-22 09:32 UTC
Labels: bug
