### ISSUE TITLE
Yarn 2 support

### ISSUE THREAD

**Issue by sacarr** [hashgraph/hedera-sdk-js#355] opened 2021-05-05 16:06 UTC
I am new to Hedera.  I initially worked through the getting started tutorial without any issues. But, I would like to use Yarn berry rather than classic so I tried the tutorial a second time using berry.  Using yarn berry, the same code and operator keys throws a TypeError at line 707 of @hasgraph/sdk/lib/transaction/Transaction.cjs.

## Steps to reproduce
I am using zsh in iTerm2 on Mac OS 11.2.3 on a 2020 MacBook Pro with node 15.0.1, npm 7.5.6 and yarn (default version 1.22.19).

Create a directory to execute the tutorial

  ```zsh
  % mkdir hello-hedera-js-sdk && cd hello-hedera-js-sdk
  ```

Switch to yarn berry, initialize a yarn project, and configure yarn to use the node-modules nodeLinker

  ```zsh 
  % yarn set version berry
  % yarn init
  % yarn config set nodeLinker node-modules
  ```
Verify the yarn configuration
```zsh
% yarn --version
2.4.1
% cat ./.yarnrc.yml
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-berry.cjs
```

Add the hedera js-sdk dependencies

  ```zsh
   % yarn add @hashgraph/sdk@2.0.19 @hashgraph/protobufjs dotenv
  ```
**Note:** unlike the documented tutorial @hashgraph/protobufjs must be explicitly added as a dependency when using yarn berry.

Create a .env file and copy your operator key

```zsh
# .env
OPERATOR_ID=<Your Operator Id>
Operator_KEY=<Your Operator Key>
```

Create index.js as per the getting started tutorial or use below
``` JavaScript
// index.js
const $protobuf = require("@hashgraph/protobufjs");
const { Client, PrivateKey, AccountCreateTransaction, AccountBalanceQuery, Hbar, AccountId, TransferTransaction } = require("@hashgraph/sdk");
require("dotenv").config();

async function main() {
    let client, operatorId;
    // Check to see which Network is requested then create a client
    if (process.env.HEDERA_NETWORK != null) {
        switch (process.env.HEDERA_NETWORK) {
            case "previewnet":
                client = Client.forPreviewnet();
                break;
            default:
                client = Client.forTestnet();
        }
    } else {
        try {
            client = await Client.fromConfigFile(process.env.CONFIG_FILE);
        } catch (err) {
            client = Client.forTestnet();
        }
    }

    // Get the operator credentials and set the client's operator
    if (process.env.OPERATOR_KEY != null && process.env.OPERATOR_ID != null) {
        const operatorKey = PrivateKey.fromString(process.env.OPERATOR_KEY);
        operatorId = AccountId.fromString(process.env.OPERATOR_ID);

        client.setOperator(operatorId, operatorKey);
    }

    console.log(`\n\n`);
    console.log(`\tGenerating keys for a new user`);
    // Generate keys for a new user
    const userKey = PrivateKey.generate();
    console.log(`\tNew user's public key = ${userKey.publicKey}`);

    // Create a new user account and fund it
    console.log(`\n\tCreating and funding a new user account`);
    const response = await new AccountCreateTransaction()
        .setKey(userKey.publicKey)
        .setInitialBalance(Hbar.fromTinybars(1000)) // 10 h
        .execute(client);
    const receipt = await response.getReceipt(client);
    const userId = receipt.accountId;

    // Confirm the new user's account balance
    console.log(`\tThe new account was successfully created and funded.`);
    const acctBalance = await new AccountBalanceQuery()
        .setAccountId(userId)
        .execute(client);
    console.log(`\tThe new user[${receipt.accountId}] account balance is: ${acctBalance.hbars.toTinybars()} tinybars`);

    // Transfer hbar from the operator account to the new user
    console.log(`\n\tTransfering 1000 tiny bars from the operator[${operatorId}]'s account to the new user[${userId}]'s account`)
    const transferTransactionResponse = await new TransferTransaction()
        .addHbarTransfer(operatorId, Hbar.fromTinybars(-1000)) // Sending account
        .addHbarTransfer(userId, Hbar.fromTinybars(1000)) // Receiving account
        .execute(client);

    const transferReceipt = await transferTransactionResponse.getReceipt(client);
    console.log(`\tThe transfer from ${operatorId}'s account to the ${userId}'s account was: ${transferReceipt.status.toString()}`);

    // Check the new user's account balance
    const userBalance = await new AccountBalanceQuery()
        .setAccountId(userId)
        .execute(client);
    console.log(`\tThe account balance after the transfer is: ${userBalance.hbars.toTinybars()} tinyBars.`);
    console.log(`\n\n`);

}

void main();
```

Add a script to run the tutorial code to package.json 

```JSON
{
  "name": "hello-hedera-js-sdk",
  "dependencies": {
    "@hashgraph/protobufjs": "^6.10.1-hashgraph.2",
    "@hashgraph/sdk": "2.0.19",
    "dotenv": "^8.5.1"
  },
  "scripts": {
    "dev": "yarn node index.js"
  }
}
```

Execute the tutorial code.  Observe a TypeError is thrown at line 707 of @hashgraph/sdk/lib/transaction/Transaction.cjs.

``` zsh
% yarn dev


	Generating keys for a new user
	New user's public key = 302a300506032b657003210 ...

	Creating and funding a new user account
./node_modules/@hashgraph/sdk/lib/transaction/Transaction.cjs:707
        signedTransactionBytes: _proto.SignedTransaction.encode(this._signedTransactions[i]).finish()
                                                         ^
TypeError: Cannot read property 'encode' of undefined
    at AccountCreateTransaction._buildTransactions (./node_modules/@hashgraph/sdk/lib/transaction/Transaction.cjs:707:58)
    at AccountCreateTransaction._makeRequest (./node_modules/@hashgraph/sdk/lib/transaction/Transaction.cjs:694:10)
    at AccountCreateTransaction.execute (./node_modules/@hashgraph/sdk/lib/Executable.cjs:233:28)
    at async main (./index.js:40:22)
```

Check to see if SignedTransaction is exported from ./node-modules/@hashgraph/proto/lib/index.js

```zsh
% grep SignedTrans ./node_modules/@hashgraph/proto/lib/index.js
% grep SignedTrans ./node_modules/@hashgraph/proto/src/index.js
```

Note SignedTransaction is not exported from either the generated lib file or the src.

Add the export of SignedTransaction.  Re-execute the tutorial script and observe the expected output.

```zsh
% echo ";const SignedTransaction=_proto.proto.SignedTransaction;exports.SignedTransaction=SignedTransaction;" >> node_modules/@hashgraph/proto/lib/index.js
% yarn dev



	Generating keys for a new user
	New user's public key = 302a300506032b657003210030aebf44b539dd8620434df5101b9a9ab0d9d313060c5c156eb3fb37e393e0ba

	Creating and funding a new user account
	The new account was successfully created and funded.
	The new user[0.0.596023] account balance is: 1000 tinybars

	Transfering 1000 tiny bars from the operator[0.0.560181]'s account to the new user[0.0.596023]'s account
	The transfer from 0.0.560181's account to the 0.0.596023's account was: SUCCESS
	The account balance after the transfer is: 2000 tinyBars.



```

## Observed Issues
1. Commit 91bb575, the commit that includes the export of SignedTransaction, is not included in the 2.0.19 release (commit 9c276f3)
2. The getting started tutorial documentation needs to be updated to make clear @hashgraph/sdk@2.0.13 does not work with yarn berry.  When using yarn berry, upgrade to an as yet to be released version of js-sdk and add @hashgraph/protobufjs as an explicit dependency.

**Comment by danielakhterov** [comment] 2021-05-06 23:12
First, thank you for the incredibly detailed issue. Secondly, I think the issue is that the way `yarn 2` aka. `berry` imports packages is very different than `yarn 1`. If you try to use `yarn 1` then I believe you shouldn't have any issues importing and using the package. As for `yarn 2` compatibility, that's something the SDK team will try to debug.

**Comment by sacarr** [comment] 2021-05-07 13:42
Thanks for the feedback on the issue description.

As I said in the issue write-up, I started with yarn classic with no problem.

I agree yarn 2 is considerably more strict about dependency declaration.  The package manager's strictness eliminates a class of difficult to diagnose latent defects. Its why I switched away from npm and yarn classic.

I also leverage yarn 2 zero-installs and plug-and-play.  But, I cannot use these features with the 2.0.19 release as I have to patch the missing export of SignedTransaction.  This is not a problem for me while I am working on tutorials, but it will be when I start work on a Ratoon app-net, probably next week.

What is the release cycle for js-SDK?

**Comment by danielakhterov** [comment] 2021-05-15 02:05
@sacarr 

I've discussed this further with the SDK team and supporting yarn 2 is not something we'll be trying to do at the moment. We'll gladly accept a PR, but since we have no idea how much effort will be required to support yarn 2, and there is not much pressure to do so we'll be tabling this for the time being.

However, we do now support `pnpm` which might be something you're interested in since it's much faster and more space efficient than yarn 1; although from what I've seen it's still still a bit slower than yarn 2.

> What is the release cycle for js-SDK?

 We don't currently have an official release cycle, but we generally make new releases whenever Hedera Services publish a new release.

**Comment by mehcode** [comment] 2021-05-16 17:42
To chime in, while we will not be trying to explicitly add support here, it does look like v2.0.20 will support yarn 2 given your detailed description of the issue you're facing.

**Comment by ziyak97** [comment] 2021-06-04 11:54
I don't have much experience with yarn 2 but shouldn't your dev script be     
"dev": "node index.js"
instead of 
"dev": "yarn node index.js"

**Comment by sacarr** [comment] 2021-06-04 12:40
Yarn 2 organizes packages differently from yarn classic enabling plug-and-play <https://yarnpkg.com/features/pnp> and zero install <https://yarnpkg.com/features/zero-installs> deployments.  While it is still possible with yarn 2 to store packages in a node-modules folder, configuring the nodeLinker to use plug-and-play moves packages into a project’s .yarn folder ensuring they are shared between workspaces.

The CLI documentation <https://yarnpkg.com/cli/node> describes how to account for yarn 2 package organization. TLDR, running yarn node index.js ensures node runs regardless of whether using the plug-and-play or node_modules configuration.

Stephanie

**Comment by mehcode** [comment] 2021-06-11 23:34
I'm going to close this. Please let me know if you have any further specific issues (from what I can tell it should work now with the latest version) but yarn 2 is going to remain something that is not explicitly supported. We would take a PR for any fixes to make it work though.

**Closed by mehcode** 2021-06-11 23:34 UTC
Labels: enhancement, help wanted, version::2
