### ISSUE TITLE
Intermittent `INVALID_NODE_ACCOUNT` error

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#1007] opened 2022-03-16 18:08 UTC
### Description

I'm conscious I don't have a reliable way to reproduce this, but I've witnessed and seen reported many instances of INVALID_NODE_ACCOUNT errors with the javascript SDK.

For example

```
error: PrecheckStatusError: transaction 0.0.30842376@1647420304.451053950 failed precheck with status INVALID_NODE_ACCOUNT
```

### Steps to reproduce

Seen on `TokenAssociateTransaction` transactions and others.

### Hedera network

mainnet, testnet, previewnet

### Version

v2.10.1

**Comment by SimiHunjan** [comment] 2022-03-16 18:13
there is a similar issue logged in the Go SDK https://github.com/hashgraph/hedera-sdk-go/issues/425. This was consistently reproduced when submitting queries. Any idea if that could be the case here?

**Comment by jackthta** [comment] 2022-03-22 21:42
Also getting this error `transaction 0.0.x@... failed precheck with status INVALID_NODE_ACCOUNT`

It seems to hit when invoking a function that uses this:

> this.client.setOperator(accountId, privateKey)
>
> await new TopicMessageSubmitTransaction()
          .setTopicId(this.topicId)
      .setMessage(message)
      .execute(this.client)

**Comment by hextulpa** [comment] 2022-04-05 21:22
When running the [hedera-example-contract-getter-setter](https://github.com/ed-marquez/hedera-example-contract-getter-setter) verbatim I get `failed precheck with status INVALID_NODE_ACCOUNT` on the final transaction "getMobileNumber"

**Comment by hextulpa** [comment] 2022-04-05 21:35
> When running the [hedera-example-contract-getter-setter](https://github.com/ed-marquez/hedera-example-contract-getter-setter) verbatim I get `failed precheck with status INVALID_NODE_ACCOUNT` on the final transaction "getMobileNumber"

I updated to latest beta SDK and it works consistently now.

**Comment by danielakhterov** [comment] 2022-04-08 22:29
@hextulpa v2.12.0 had this issue somewhat consistently, but it was fixed in v2.12.0.

As for this issue, I think it's resolved, but since we weren't necessarily able to reproduce I'll just create an e2e test that execute 1000 crypto transfers _without_ setting the node account IDs. Hopefully this will hit the `INVALID_NODE_ACCOUNT`. Otherwise, I'll close until someone hits this again.

**Comment by danielakhterov** [comment] 2022-04-27 00:55
To reiterate, will open if someone hits this again, but as of right now I'm not able to hit this issue even after running a crypto transfer test for a few hours.

**Comment by AdriMsM91** [comment] 2022-07-07 15:59
Hello, from yesterday we're having this problem when we're trying to create an Account in Testnet. Its giving us this error from each 10 times like 7 times, so 3 of them is creating the AccountID correctly. We're from Europe If It can make any diffrence.

`[ERROR] - New account creation:  PrecheckStatusError: transaction 0.0.30812036@1657127705.635168680 failed precheck with status INVALID_NODE_ACCOUNT`

**Comment by danielakhterov** [comment] 2022-08-15 15:26
Firstly, I want to say I did review the code a bit with regards to node account IDs and how we use them. I didn't see anything that was obviously wrong, but I could have missed something. Secondly, I spoke with @gregscullard again and he hasn't seemed to hit this in awhile which makes me think this issue was solved at one point, but we didn't know it. I also re-ran my 4000 crypto transfers example without using `setNodeAccountIds()` to see if I could hit this error, but everything went smoothly. Thirdly, @AdriMsM91 I don't think being in Europe would make any difference to the SDK since it operates strictly on IP addresses. However, what I would recommend is making sure you're on the latest SDK version and if you really want to avoid any potential issue with node account IDs I'd suggest enabling `[Client|Transaction].signOnDemand`. This option would choose a random node from the entire network per attempt and build and sign appropriate requests per attempt instead of building and signing in `Transaction.freezeWith()` and `Transaction.sign[With|WithOperator]()`. Lastly, if you have found a way to reproduce this issue I'm all ears, but as of right now I can't and so I'm closing this issue again.

**Closed by danielakhterov** 2022-08-15 15:26 UTC
Labels: bug, p1

**Comment by AdriMsM91** [comment] 2023-06-18 08:59
Good morning @gregscullard @janaakhterov from KabilaApp we keep getting this error each day around 500 and 8000 times in our services (Launchpad and Tools). We're using the version 2.26.0 of the JS SDK and we're not setting any node, we're just doing:

`Client.forNetwork('mainnet')`
