### ISSUE TITLE
Unexpected SDK change: PrivateKey object now requires fromStringECDSA instead of fromString to define client credentials

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#1470] opened 2023-02-21 17:44 UTC
### Description

As of two weeks ago (approximately) the following code was working ok to import credentials from `.env` and initialize the client using both ECDSA and ED25519 keys:
```
const operatorId = AccountId.fromString(process.env.OPERATOR_ID);
const operatorKey = PrivateKey.fromString(process.env.OPERATOR_PVKEY);
const network = process.env.HEDERA_NETWORK;
const client = Client.forNetwork(network).setOperator(operatorId, operatorKey);
```

Today, a new INVALID_SIGNATURE error was received with the existing code. After a few minutes of troubleshooting, it was discovered that the following change was required:
`const operatorKey = PrivateKey.fromStringECDSA(process.env.OPERATOR_PVKEY);`

This change triggered a few questions:

- When was this change introduced? iirc, just .fromString worked for both ECDSA and ED25519
- Was this change documented in the [SDK notes or elsewhere](https://github.com/hashgraph/hedera-sdk-js/releases?page=1)?
- What is the reasoning for requiring explicit declaration of the key type from the user?
- Would it be a better experience for the user if the SDK handled all key types with the same method?

One of my concerns with this is that it's a significant change with the potential to affect/break a lot of applications
(a large number of applications that use our SDKs may be including those lines in their code)

### Steps to reproduce

Tried multiple version.

- Can't remember which one I started with (lol)
- Then upgraded to v2.20
- Then downgraded to v2.19.0

Saw the issue with all

### Hedera network

previewnet

### Version

v2.20

### Operating system

Windows

**Comment by ochikov** [comment] 2023-02-22 20:08
Hello @ed-marquez, we've managed to test it and indeed the method `fromString` now does not work with ECDSA private keys. We don't have any changes in the SDKs related to such functionality. We even tested with a really old version: 2.18.0 and it's not working. As far as I remember, I used to work like you, only with `fromString` using the ECDSA method. Something that comes to my mind is the change of the Hedera Portal ECDSA keys format. Did you copy your key in the previous 2-3 weeks from the portal, when the testnet network was reset? The issue is coming from the fact that we are trying first to create ED25519 key when the `fromString` is used and now both keys are 32 bytes. We are continuing to investigate the possible fix, so the users can use the `fromString` with both ECDSA and ED25519 keys.

**Comment by ed-marquez** [comment] 2023-02-22 21:18
Thanks @ochikov - yes, in fact, the only thing that changed over the past two weeks in my code is that I copied my keys from the portal within that time period and noticed that the portal now gives a shorter version of the keys without the prefix `302e020100300506032b657004220420` that it used to include before.

I agree that keeping the ability to use `fromString` with both key types would be ideal - so, glad to hear the team is investigating that route.

**Comment by SimiHunjan** [comment] 2023-02-23 01:30
It may be that we need the portal to display the keys with the prefix?

**Comment by petreze** [comment] 2023-02-23 11:44
@SimiHunjan 
This might be the case, yes. Currently I'm not able to find if there is a chance to differ both keys at all if they are exact same length..

**Comment by ochikov** [comment] 2023-02-24 07:21
@ed-marquez We manage to identify the problem. The prefix of the key in the portal is missing. I am going to ping you again when this is fixed.

**Comment by ochikov** [comment] 2023-02-27 07:54
Hello @ed-marquez, the team that supports the Hedera Portal now applies the fixes and I've tested it on the SDK side. Everything is working as expected. I can use `fromString` both with ED25519 and ECDSA key types. I will close the issue. 
Thank you very much for arising it.

**Closed by ochikov** 2023-02-27 07:54 UTC
Labels: bug
