### ISSUE TITLE
sdk incompatible with react-native 

### ISSUE THREAD

**Issue by vivek2910** [hashgraph/hedera-sdk-js#236] opened 2020-03-31 14:43 UTC
Tried to use the js-sdk with react-native application but got error :
` Error: Unable to resolve module crypto from node_modules/@hashgraph/sdk/lib/crypto/util.js: crypto could not be found within the project.`

**Comment by Cooper-Kunz** [comment] 2020-03-31 16:15
Is it possible that this is a duplicate of #229? Or do you believe that you're experiencing a different issue?

**Comment by vivek2910** [comment] 2020-03-31 16:18
yaa this is kind of same but getting error for a different module that is used in js-sdk, specifically the crypto module.

**Comment by mehcode** [comment] 2020-03-31 17:38
Let's track eventual simple react native support in the one issue. React native should work if you use rn-nodeify or at least that's what I believe given what I remember about React Native.

**Closed by mehcode** 2020-03-31 17:38 UTC
