### ISSUE TITLE
Cannot pass TransferTransaction to setScheduledTransaction() in v2.13

### ISSUE THREAD

**Issue by bluemonad** [hashgraph/hedera-sdk-js#1085] opened 2022-04-19 14:52 UTC
### Description

When trying to pass a `TransferTransaction` to `setScheduledTransaction` I get an error:

> `TS2345: Argument of type 'TransferTransaction' is not assignable to parameter of type 'Transaction'.
  Property 'override' is protected in type 'TransferTransaction' but public in type 'Transaction'.`

This happens in v2.13, but I believe it started in v2.12. This worked well in v2.11.3 and prior versions.

### Steps to reproduce

1. Create a `TransferTransaction`
3. Create a schedule transaction with `new ScheduleCreateTransaction()`
4. Pass the `TransferTransaction` as a parameter to the method `setScheduledTransaction()` of the schedule transaction
5. Try to build / run the code

### Hedera network

mainnet, testnet

### Version

v0.2.13

**Comment by danielakhterov** [comment] 2022-04-21 02:14
Huh, the error isn't _very_ helpful because `override` is not a property, but since you're getting the error I think we need to create a unit test for each schedulable transaction. Also, it may be wise for us to try and enable `tsc` on our unit tests.

**Comment by SimiHunjan** [comment] 2022-04-25 22:58
@bluemonad do you have any additional information to help troubleshoot the issue you submitted?

**Comment by danielakhterov** [comment] 2022-04-28 00:59
@bluemonad the linked PR shows me just randomly using what you aforementioned and I don't seem to get any errors with `tsc` or `eslint`. I also ran the example which ran fine; although the scheduled transaction wasn't executed.
Closing until we get more details since I was not able to reproduce.

**Closed by danielakhterov** 2022-04-28 00:59 UTC
Labels: bug
