### ISSUE TITLE
setMaxTransactionFee not honoring limit when specified for the client

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sdk-js#895] opened 2022-01-28 20:06 UTC
### Description

This issue is the reverse of [issue 894](https://github.com/hashgraph/hedera-sdk-js/issues/894), but with setMaxTransactionFee. 

Setting the max transaction payment to 0.01 Hbar for the client is not being honored in the JS SDK:
`client.setMaxTransactionFee(new Hbar(0.01));`

When the limit is set for for an individual transaction, the limit is honored.
`FileCreateTransaction().setMaxTransactionFee(new Hbar(0.5))`

The limit should be honored in both cases.

### Steps to reproduce

1. Go to [this code Sandbox](https://codesandbox.io/s/hedera-example-contract-getter-setter-8whrs?file=/index.js) and enter your testnet credentials in .env (or download the .js, .sol, and .bin files if you wanna try locally)

2. See lines 31 and 78. (.setMaxTransactionFee(new Hbar(X)))

3. Run index.js - notice that those limits are honored. Try reducing them too... See error: 
`transaction 0.0.2520793@1643400128.976450413 failed precheck with status INSUFFICIENT_TX_FEE`
 
4. then try adding the transaction payment limit to the client (line 21 = `client.setMaxTransactionFee(new Hbar(0.01));`), run index.js 

5. The error should occur but it doesn't

### Hedera network

testnet

### Version

v2.7.1

### Operating system

Windows

**Comment by danielakhterov** [comment] 2022-01-29 06:01
Reviewing your code, we should elaborate on how the `maxTransactionFee` is set. Here is the code snippet from the SDK:
```javascript
        this._maxTransactionFee =
            client != null && this._maxTransactionFee == null
                ? client.maxTransactionFee
                : this._maxTransactionFee;
```
The behavior works as intended from what I can tell; setting the fee on a request takes priority over the fee that is set on client. If you'd like the request to respect the client's max transaction then it must not be set on the particular request. The expected behavior is not to take the minimum of the two. Hopefully that clears up the confusion.

**Comment by ed-marquez** [comment] 2022-01-31 17:40
Your response helps and the default behavior makes sense. However, **there is a bug**. Perhaps my repro steps were slightly unclear. I wasn't referencing a case where you specify the setMaxTransactionFee() for both the request and the client. 

In step 4, I meant: add the max fee to the client while removing it from the request. You will find that the limit is not honored. 
If you set the limit low enough for the request, the request fails. If you set it to the same low value for the client (after removing it for the request), it does not fail. 

Can you please try it and let me know if I'm missing something? Thanks!

**Comment by danielakhterov** [comment] 2022-01-31 21:21
Ah, yea it was a little unclear to me about that, but what you're saying now makes sense. Also, I took a bit of a closer look at our transaction fee handling and it seems the code snippet above never returns false because `this._maxTransactionFee` is always set.

**Comment by danielakhterov** [comment] 2022-01-31 21:35
Fixed on `develop`, will be released today. https://github.com/hashgraph/hedera-sdk-js/commit/ceb51d9330a971e33c574fc9f0a9f76ced39d26f

**Closed by danielakhterov** 2022-01-31 21:35 UTC
Labels: bug

**Comment by ed-marquez** [comment] 2022-01-31 22:04
Awesome! Thank you for the fast response on this.
