### ISSUE TITLE
Hedera.js + React Native support

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-sdk-js#229] opened 2020-03-23 23:20 UTC
The community could use some guidance on the best way to make Hedera API calls from a React Native app running on IOS/Android. It seems that most are running into trouble with the gRPC binaries on iOS.

> Error: {"code":"MODULE_NOT_FOUND"} => Error: Failed to load gRPC binary module because it was not installed for the current system

Users are already reporting trying the` rn-nodeify` package, and still reporting the issue. 

Maybe even providing a working React native starter project could be a good, long term solution.

<hr/>

Rob, the CTO of Ledgerama, is driving this forward as it is currently blocking their development.

I'll see if I can get him to chime in here.

**Comment by robkainz** [comment] 2020-03-24 11:41
We are in the process of developing mobile wallet functionality (prereq for our Treasure6 vision). Our first goal is an ios version of the wallet in a bare React Native project using the hedera-sdk-js library. Vishal, from Rejolut, told me they could not get this working in production because they couldn't deploy an ios binary for the grpc dependency that the Hedera sdk requires (it worked only in development, on a simulator from what I understand). This also seems to be the problem I am seeing if I use the nodejs-mobile-react-native library to spin up a node server on another thread. Ideally though, I don't even want to have to do that. I just want to be able to "yarn install" the Hedera sdk and be able to make calls right out of the box. 

Without using nodejs-mobile-react-native and trying to get an account balance I run into an SSL issue:

`2020-03-24 06:25:45.026968-0400 Ledgerama[6286:1627008] [BoringSSL] boringssl_context_handle_fatal_alert(1872) [C12.1:2][0x7f81d2f01da0] write alert, level: fatal, description: protocol version
2020-03-24 06:25:45.027140-0400 Ledgerama[6286:1627008] [BoringSSL] boringssl_context_error_print(1862) boringssl ctx 0x600000a99e50: 140195564412776:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl_Sim/boringssl-283.60.3/ssl/tls_record.cc:242:
`

I'm a mobile app newbie and honestly don't yet know how to solve this problem in an xcode simulator (perhaps I need to deploy a root certificate somehow). But even if I could, I suspect this will only work in the simulator on Mac OSX, because as Vishal pointed out, if I look in node_modules/grpc/src/node/extension_binary I see only the darwin binary, not an ios one:

node-v79-darwin-x64-unknown

I also messed around with the nodejs-mobile-react-native library as described earlier, and when trying to call the Hedera SDK there using their example as a guide I get this error: 

`LOG  From node: Error: {"code":"MODULE_NOT_FOUND"} => Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v64-ios-x64-unknown
Found: [node-v79-darwin-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/Users/robertkainz/Library/Developer/CoreSimulator/Devices/AEC2A1D0-44A4-4191-9513-17B5E9E69F90/data/Containers/Bundle/Application/5BC2035E-9692-4DA1-8954-55DA4E16D8D7/Ledgerama.app/nodejs-project/node_modules/grpc/src/node/extension_binary/node-v64-ios-x64-unknown/grpc_node.node'
  at Anonymous function (/Users/robertkainz/Library/Developer/CoreSimulator/Devices/AEC2A1D0-44A4-4191-9513-17B5E9E69F90/data/Containers/Bundle/Application/5BC2035E-9692-4DA1-8954-55DA4E16D8D7/Ledgerama.app/nodejs-project/node_modules/grpc/src/grpc_extension.js:55:5)
  at Module.prototype._compile (internal/modules/cjs/loader.js:688:5)
  at Module._extensions[.js] (internal/modules/cjs/loader.js:699:3)
  at Module.prototype.load (internal/modules/cjs/loader.js:598:3)
  at tryModuleLoad (internal/modules/cjs/loader.js:537:5)
  at Module._load (internal/modules/cjs/loader.js:529:3)
  at Module.prototype.require (internal/modules/cjs/loader.js:636:3)
  at require (internal/modules/cjs/helpers.js:20:7)
  at Anonymous function (/Users/robertkainz/Library/Developer/CoreSimulator/Devices/AEC2A1D0-44A4-4191-9513-17B5E9E69F90/data/Containers/Bundle/Application/5BC2035E-9692-4DA1-8954-55DA4E16D8D7/Ledgerama.app/nodejs-project/node_modules/grpc/src/client_interceptors.js:144:1)
  at Module.prototype._compile (internal/modules/cjs/loader.js:688:5)`

I followed the direction there and tried "npm rebuild", even "npm rebuild --build-from-source", and those did not work. I still got the same error. 

That's as far as I got. I didn't go too deep into trying to find a way to build an ios target for the grpc dependency. 

Vishal said one option is to use the Hedera-Rust-SDK like Rejolut did (or use their Hedera-IOS-SDK which forks it) and call it natively, but it looks like in doing so I would need to learn Rust, implement methods in lib.rs to expose the functionality I need from the Rust SDK and write some bridge code so that my RN app can make the calls. It's all doable, but it's more work than I would like to do and I don't want to rely on a Hedera community-supported SDK that Vishal said is really not being maintained.

As Cooper suggested, I think a demo project that includes all binaries needed for production deployment on both IOS/Android would be very welcome for the mobile app developer community who desires to integrate Hedera services into their applications. 

Rob Kainz
CTO, Ledgerama LLC
http://ledgerama.com

**Comment by robkainz** [comment] 2020-04-03 16:38
@mehcode Were you able to reproduce the issue or come up with a working React Native boot project? In about a week or two I intend to revisit this and would love to see a working solution by then if possible. Let me know if I can be of any help. Thanks.

**Comment by mehcode** [comment] 2020-04-03 23:17
It sadly isn't a priority at this time. However, the recent work to remove all usage of node crypto should have resolved a lot of potential blockers here. I'd wager that master may "just work" in react native now or at least it might be a lot easier to tie it in.

**Comment by ChALkeR** [comment] 2020-07-24 19:34
I believe #261 is highly related and might be the main blocker.

`crypto` module can be polifilled with https://github.com/crypto-browserify and bundlers should already do that.

`grpc` is a native module though, and it can't be run without Node.js, unless replaced with `@grpc/grpc-js`.

**Comment by mehcode** [comment] 2020-07-24 19:38
This isn't something we plan to support in any reasonable timeline. Ideally, a React Native SDK would be a thin layer over the Android and iOS SDKs.

**Closed by mehcode** 2020-07-24 19:38 UTC
