### ISSUE TITLE
Add EthereumTransaction to JS SDK

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-sdk-js#1102] opened 2022-04-27 16:00 UTC

**Comment by danielakhterov** [comment] 2022-04-27 20:24
Is this a duplicate of https://github.com/hashgraph/hedera-sdk-js/issues/1076 which has been done for a little over a week: https://github.com/hashgraph/hedera-sdk-js/pull/1083/files#diff-62ba10554d1612813c4dd21089501afa5455091b2b946d146af917f413049fa4R50 We did go with the name of `ContractEvmTransaction` which may be why it was confusing. The definitely think we should go with the `Contract` prefix, but not sure if `Evm` is the right name; I just wanted something shorter than `Ethereum`, maybe `Eth`?

**Comment by danielakhterov** [comment] 2022-04-27 20:50
I take it back, after talking with Sean I'm convinced we shouldn't prefix prefix with `Contract` because it applies to more than just contract transactions, but the reason this was confusing to begin with is because `EthereumTransaction` is under the `SmartContractServices`.

**Closed** 2022-04-30 03:41 UTC
