### ISSUE TITLE
fix: TopicMessageQuery#unsubscribe() attempts to re-subscribe

### ISSUE THREAD

**Issue by bguiz** [hashgraph/hedera-sdk-js#2222] opened 2024-03-26 09:08 UTC
## 🆕🐥 First Timers Only

This issue is reserved for people who have never contributed to [Hedera](https://hedera.com) or any open source project in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by [**'good first issue'**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Ahashgraph+archived%3Afalse+label%3A%22good+first+issue%22+) is to help you make your first contribution to Hedera.

### Problem
When using TopicMessageQuery to subscribe to a topic and then attempting to unsubscribe, an error is thrown that suggests the system is trying to re-subscribe rather than cleanly disconnect:

```js
  const subscription = new TopicMessageQuery()
    .setTopicId(topicId)
    .subscribe(client, myCallback);
  subscription.unsubscribe();
```

This results in the following error:

```js
Error subscribing to topic 0.0.3745107 during attempt 0. Waiting 250 ms before next attempt: 1 CANCELLED: Cancelled on client
```

The **expected behavior** is that unsubscribe() should terminate the subscription without attempting a re-subscription. This error likely affects users working on subscribing to topics in the Hedera network and needs a fix to ensure proper subscription management.

### Steps to reproduce

1. Set up this [project](https://github.com/hedera-dev/hcs-skills/)
2. Execute the script provided in the repo, located at: [checkpoint-subscribe.js](https://github.com/hedera-dev/hcs-skills/blob/completed/scripts/checkpoint-subscribe.js).

### Expected Behavior
unsubscribe() should end the subscription without attempting any further reconnection attempts or retries.

### Additional context

-  Relevant discussion can be found in the Slack thread: [TopicMessageQuery Conversation ](https://swirldslabs.slack.com/archives/C0453UVBR42/p1711032195458069)

### Hedera network

testnet

### Version

2.42.0

### Operating system

macOS

## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow. More information and concrete samples for shell commands for each step can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md) file.
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] **Claim this issue:** Comment below that you are interested in working on the issue
- [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
- [ ] **Fork the repository:** You can do that in GitHub (by simply clicking the 'fork' button).
- [ ] **Check out the forked repository**
- [ ] **Create a feature branch** for the issue. We do not have a hard naming definition for branches but it is best practice to prefix the branch name with the issue id.
- [ ] **Solve the issue** in your branch.
- [ ] **Commit your changes:** Here, it is needed to add `sign-off` information to the commit to accept the "Developer Certificate of Origin" (https://developercertificate.org). More details can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md)
- [ ] **Start a Pull Request (PR)**: We have a pattern for naming pull requests that a GitHub Action checks. We use that pattern to support the creation of automatic release notes.
- [ ] **Check GitHub Actions:** Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error do not hesitate to add a comment to the PR and ask the Hedera developer community for support.
- [ ] **Wait for reviews:** Members of the Hedera developer community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will start a discussion with you and describe the next steps for solving the problem.
- [ ] **You did it 🎉:** We will merge the fix in the develop branch. Thanks for being part of the Hedera community as an open-source contributor ❤️

## 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

## 🤔 Additional Information

If you have any questions, just ask us directly in this issue by adding a comment. You can join our community chat at [Discord](https://hedera.com/discord). A general manual about open-source contributions can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by Jexsie** [comment] 2024-10-05 16:18
Hey @bguiz, the linked file `checkpoint-subscribe.js` is broken. Did you mean [`checkpoint-04-subscribe.js`](https://github.com/hedera-dev/hcs-skills/blob/completed/scripts/checkpoint-04-subscribe.js)?  Kindly update on how to replicate the issue

**Comment by Atharva1723** [comment] 2024-10-06 10:36
Can I work on this issue?

**Comment by raymondjoseph02** [comment] 2024-10-06 11:30
Can I work on this? I have never contributed to an open-source project before.

**Comment by SIDHARTH20K4** [comment] 2024-10-07 00:43
Hey @bguiz 
I would like to work on this issue

**Comment by Manav958** [comment] 2024-10-08 12:45
Hey @hendrikebbers i have an update regarding the issue

i tested various scenarios and i think its working okay
![Screenshot 2024-10-08 181209](https://github.com/user-attachments/assets/5f7f2d11-572f-415f-9d43-8914b9752818)

this is the screenshot of the output
the error due to continue subscribe process is not coming
is there anything else to do?
Thankyou .

**Comment by agadzhalov** [comment] 2024-10-08 14:05
Hi @Manav958, in order to reproduce it, can you test this [snippet](https://gist.github.com/agadzhalov/6fb46fb02631e4e42d1e8cc5cabc2454) against testnet, at the end you should receive 
```
Error subscribing to topic 0.0.4963755 during attempt 0. Waiting 250 ms before next attempt: 1 CANCELLED: Cancelled on client
```

**Comment by Manav958** [comment] 2024-10-08 17:41
Hey @agadzhalov i tested the snippet and after 3 messages got sent it threw this error.
what further steps should i take?

**Comment by agadzhalov** [comment] 2024-10-10 12:32
Hi @Manav958, the expected result is to fix the bug and at the end the error not to be thrown. As a hint you can spend more time looking in the different `Topic` classes, also you can investigate the `subscribe` and `unsubscribe` methods.

> The expected behavior is that unsubscribe() should terminate the subscription without attempting a re-subscription

**Comment by Manav958** [comment] 2024-10-11 13:09
Ok ,
I am improving on it

**Comment by hendrikebbers** [comment] 2024-10-14 07:57
Hi all,
@Manav958, thank you for the effort. I like how you ask questions. Go forward.
@Jexsie, It Looks like you created a PR without being assigned to the issue. Please always make sure that you are assigned. Otherwise, two people will work on the issue.

I can not say if the PR by @Jexsie fixed the complete issue. Here I would like to hear @agadzhalov 
If it fixes all we will find a good other issue for @Manav958 Otherwise we can merge it and let @Manav958 do the rest of the work. By doing so you both did a PR :)

**Comment by Manav958** [comment] 2024-10-14 08:49
Thank you @hendrikebbers .
If @Jexsie agrees we can work together on the issue , two better than one.

**Comment by agadzhalov** [comment] 2024-10-14 09:47
Hi @Manav958 @hendrikebbers. I've just tested @Jexsie's fix and seems to be working as expected. So may be @Manav958 can focus on some other good first issues

**Closed** 2024-10-25 08:51 UTC
Labels: bug, good first issue, hacktoberfest
