### ISSUE TITLE
Inaccurate automatic cost calculation causes transactions to fail

### ISSUE THREAD

**Issue by anvabr** [hashgraph/hedera-sdk-js#1425] opened 2023-01-30 16:35 UTC
### Description

We are trying to execute `ContractCallQuery`,  it appears the cost of this transactions is calculated incorrectly (too low) which causes transaction to fail as in this example:

`transaction 0.0.11205@1675091501.521603607 failed precheck with status INSUFFICIENT_TX_FEE`

We attempted to use `setMaxQueryPayment` which does not help, the error still happens.

### Steps to reproduce

See problem description above.

### Additional context

When we use `setQueryPayment` and set it high the transactions go through. 

Looking at the comments and the code in the example [here](https://github.com/hashgraph/hedera-sdk-js/blob/e0cd39c84ab189d59a6bcedcf16e4102d7bb8beb/examples/create-stateful-contract.js#L158) it seems this problem is known to the SDK developers as it says:

```
        // Set the query payment explicitly since sometimes automatic payment calculated
        // is too low
        .setQueryPayment(new Hbar(3))
```

For production system this approach is clearly not acceptable.

### Hedera network

mainnet, testnet

### Version

v2.19.2

### Operating system

None

**Comment by ochikov** [comment] 2023-02-01 16:45
[v2.20.0-beta.4](https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.20.0-beta.4) Should fix it.

**Comment by Neurone** [comment] 2023-02-02 11:45
Hi @ochikov , I don't think #1430 `Hbar.fromString(cost.toBigNumber().plus(0.001).toString());` is a viable fix for this.

If the problem is in the estimate function of the consensus nodes, as it seems, this is not something to be solved at the SDK level.

Also, this fix raises the payment of all queries across the board; even for those queries, the consensus node correctly computed the cost, and it makes the JS SDK works differently from the other SDKs (they sometimes multiply the cost by 1.1, sometimes they don't, etc.), so it can just add confusion to the topic.
 
The code above can be a temporary workaround we suggest to application developers if they face this issue while we wait for the consensus node to update the estimate function. We can also add a helper function, for example, something like `getSafeCost()`, that developers can use in their `.setQueryPayment` function, but I think the base function should be "clean" and without workarounds.

I'll open a dedicated issue on the hedera-services repo, but I suggest amending the modification

**Comment by ochikov** [comment] 2023-02-02 11:54
Hello, we've synced with services and I've pushed another commit with the [this](https://github.com/hashgraph/hedera-sdk-js/pull/1431/commits/d6536c4222233de514d2f7d6104f164cba56b193) fix. I agree that it's not in the SDK, but with this temporary fix, we can be on the same values. 
We already raised the issue to the services team. Thank you for opening an issue there.

**Comment by ochikov** [comment] 2023-02-14 13:45
https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.20.0

**Closed** 2023-02-14 14:02 UTC
Labels: bug
